INSERT INTO stockalert.product (id, quantity, restock_rounds) VALUES
    (4, 0, 0);

INSERT INTO product_user_notification (user_id, product_id, is_notification_enabled) VALUES
                                                                                             (1, 4, false),
                                                                                             (2, 4, false),
                                                                                             (3, 4, false),
                                                                                             (4, 4, false),
                                                                                             (5, 4, false),
                                                                                             (6, 4, false),
                                                                                             (7, 4, false),
                                                                                             (8, 4, false),
                                                                                             (9, 4, false),
                                                                                             ( 10, 4, false),
                                                                                             ( 11, 4, false),
                                                                                             ( 12, 4, false),
                                                                                             ( 13, 4, false),
                                                                                             ( 14, 4, false),
                                                                                             ( 15, 4, false),
                                                                                             ( 16, 4, false),
                                                                                             ( 17, 4, false),
                                                                                             ( 18, 4, false),
                                                                                             ( 19, 4, false),
                                                                                             ( 20, 4, false);

-- Product 테이블에 삽입되는 데이터
INSERT INTO stockalert.product (id, quantity, restock_rounds) VALUES
                                                   (1, 0, 0),
                                                   (2, 0, 0),
                                                   (3, 0, 0);

-- ProductUserNotification 테이블에 삽입되는 데이터 (notification_enabled 컬럼 제거)
INSERT INTO product_user_notification (id, user_id, product_id, is_notification_enabled) VALUES
                                                                  (1, 1, 1, false),
                                                                  (2, 2, 1, false),
                                                                  (3, 3, 1, false),
                                                                  (4, 4, 1, false),
                                                                  (5, 5, 1, false),
                                                                  (6, 6, 1, false),
                                                                  (7, 7, 1, false),
                                                                  (8, 8, 1, false),
                                                                  (9, 9, 1, false),
                                                                  (10, 10, 1, false),
                                                                  (11, 11, 1, false),
                                                                  (12, 12, 1, false),
                                                                  (13, 13, 1, false),
                                                                  (14, 14, 1, false),
                                                                  (15, 15, 1, false),
                                                                  (16, 16, 1, false),
                                                                  (17, 17, 1, false),
                                                                  (18, 18, 1, false),
                                                                  (19, 19, 1, false),
                                                                  (20, 20, 1, false),
                                                                  (21, 21, 1, false),
                                                                  (22, 22, 1, false),
                                                                  (23, 23, 1, false),
                                                                  (24, 24, 1, false),
                                                                  (25, 25, 1, false),
                                                                  (26, 26, 1, false),
                                                                  (27, 27, 1, false),
                                                                  (28, 28, 1, false),
                                                                  (29, 29, 1, false),
                                                                  (30, 30, 1, false),
                                                                  (31, 31, 1, false),
                                                                  (32, 32, 1, false),
                                                                  (33, 33, 1, false),
                                                                  (34, 34, 1, false),
                                                                  (35, 35, 1, false),
                                                                  (36, 36, 1, false),
                                                                  (37, 37, 1, false),
                                                                  (38, 38, 1, false),
                                                                  (39, 39, 1, false),
                                                                  (40, 40, 1, false),
                                                                  (41, 41, 1, false),
                                                                  (42, 42, 1, false),
                                                                  (43, 43, 1, false),
                                                                  (44, 44, 1, false),
                                                                  (45, 45, 1, false),
                                                                  (46, 46, 1, false),
                                                                  (47, 47, 1, false),
                                                                  (48, 48, 1, false),
                                                                  (49, 49, 1, false),
                                                                  (50, 50, 1, false),
                                                                  (51, 51, 1, false),
                                                                  (52, 52, 1, false),
                                                                  (53, 53, 1, false),
                                                                  (54, 54, 1, false),
                                                                  (55, 55, 1, false),
                                                                  (56, 56, 1, false),
                                                                  (57, 57, 1, false),
                                                                  (58, 58, 1, false),
                                                                  (59, 59, 1, false),
                                                                  (60, 60, 1, false),
                                                                  (61, 61, 2, false),
                                                                  (62, 62, 2, false),
                                                                  (63, 63, 2, false),
                                                                  (64, 64, 2, false),
                                                                  (65, 65, 2, false),
                                                                  (66, 66, 2, false),
                                                                  (67, 67, 2, false),
                                                                  (68, 68, 2, false),
                                                                  (69, 69, 2, false),
                                                                  (70, 70, 2, false),
                                                                  (71, 71, 2, false),
                                                                  (72, 72, 2, false),
                                                                  (73, 73, 2, false),
                                                                  (74, 74, 2, false),
                                                                  (75, 75, 2, false),
                                                                  (76, 76, 2, false),
                                                                  (77, 77, 2, false),
                                                                  (78, 78, 2, false),
                                                                  (79, 79, 2, false),
                                                                  (80, 80, 2, false),
                                                                  (81, 81, 2, false),
                                                                  (82, 82, 2, false),
                                                                  (83, 83, 2, false),
                                                                  (84, 84, 2, false),
                                                                  (85, 85, 2, false),
                                                                  (86, 86, 2, false),
                                                                  (87, 87, 2, false),
                                                                  (88, 88, 2, false),
                                                                  (89, 89, 2, false),
                                                                  (90, 90, 2, false),
                                                                  (91, 91, 2, false),
                                                                  (92, 92, 2, false),
                                                                  (93, 93, 2, false),
                                                                  (94, 94, 2, false),
                                                                  (95, 95, 2, false),
                                                                  (96, 96, 2, false),
                                                                  (97, 97, 2, false),
                                                                  (98, 98, 2, false),
                                                                  (99, 99, 2, false),
                                                                  (100, 100, 2, false),
                                                                  (101, 101, 2, false),
                                                                  (102, 102, 2, false),
                                                                  (103, 103, 2, false),
                                                                  (104, 104, 2, false),
                                                                  (105, 105, 2, false),
                                                                  (106, 106, 2, false),
                                                                  (107, 107, 2, false),
                                                                  (108, 108, 2, false),
                                                                  (109, 109, 2, false),
                                                                  (110, 110, 2, false),
                                                                  (111, 111, 2, false),
                                                                  (112, 112, 2, false),
                                                                  (113, 113, 2, false),
                                                                  (114, 114, 2, false),
                                                                  (115, 115, 2, false),
                                                                  (116, 116, 2, false),
                                                                  (117, 117, 2, false),
                                                                  (118, 118, 2, false),
                                                                  (119, 119, 2, false),
                                                                  (120, 120, 2, false),
                                                                  (121, 121, 3, false),
                                                                  (122, 122, 3, false),
                                                                  (123, 123, 3, false),
                                                                  (124, 124, 3, false),
                                                                  (125, 125, 3, false),
                                                                  (126, 126, 3, false),
                                                                  (127, 127, 3, false),
                                                                  (128, 128, 3, false),
                                                                  (129, 129, 3, false),
                                                                  (130, 130, 3, false),
                                                                  (131, 131, 3, false),
                                                                  (132, 132, 3, false),
                                                                  (133, 133, 3, false),
                                                                  (134, 134, 3, false),
                                                                  (135, 135, 3, false),
                                                                  (136, 136, 3, false),
                                                                  (137, 137, 3, false),
                                                                  (138, 138, 3, false),
                                                                  (139, 139, 3, false),
                                                                  (140, 140, 3, false),
                                                                  (141, 141, 3, false),
                                                                  (142, 142, 3, false),
                                                                  (143, 143, 3, false),
                                                                  (144, 144, 3, false),
                                                                  (145, 145, 3, false),
                                                                  (146, 146, 3, false),
                                                                  (147, 147, 3, false),
                                                                  (148, 148, 3, false),
                                                                  (149, 149, 3, false),
                                                                  (150, 150, 3, false),
                                                                  (151, 151, 3, false),
                                                                  (152, 152, 3, false),
                                                                  (153, 153, 3, false),
                                                                  (154, 154, 3, false),
                                                                  (155, 155, 3, false),
                                                                  (156, 156, 3, false),
                                                                  (157, 157, 3, false),
                                                                  (158, 158, 3, false),
                                                                  (159, 159, 3, false),
                                                                  (160, 160, 3, false),
                                                                  (161, 161, 3, false),
                                                                  (162, 162, 3, false),
                                                                  (163, 163, 3, false),
                                                                  (164, 164, 3, false),
                                                                  (165, 165, 3, false),
                                                                  (166, 166, 3, false),
                                                                  (167, 167, 3, false),
                                                                  (168, 168, 3, false),
                                                                  (169, 169, 3, false),
                                                                  (170, 170, 3, false);
